apiVersion: apps/v1
kind: Deployment
metadata:
  name: apidoc-deploy
  namespace: apidoc
  labels:
    app: apidoc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apidoc
  template:
    metadata:
      labels:
        app: apidoc
    spec:
      containers:
      - name: apidoc
        image: apidoc  # on server
        # image: commonui
        ports: 
        - name: http
          containerPort: 8080
#        volumeMounts:
#          - name: commonui-config
#            mountPath: /etc/config/configMap.yaml
#      volumes:
#        - name: commonui-config
#          hostPath: 
#            path: /Users/sehwan/ICIS-TR/spring-openapi-k8s/openapi-common-ui/src/main/resources/configMap.yaml
          
--- 
apiVersion: v1
kind: Service
metadata:
  name: apidoc-service
  namespace: apidoc
spec:
  # type: NodePort
  selector:
    app: apidoc
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http
      # nodePort: 32180
---
#apiVersion: rbac.authorization.k8s.io/v1
#kind: Role
#metadata:
#  namespace: apidoc
#  name: namespace-reader
#rules:
#  - apiGroups: ["", "extensions", "apps"]
#    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
#    verbs: ["get", "list", "watch"]
#
#---
#
#apiVersion: rbac.authorization.k8s.io/v1
#kind: RoleBinding
#metadata:
#  name: namespace-reader-binding
#  namespace: apidoc
#subjects:
#- kind: ServiceAccount
#  name: default
##  name: dev
#  apiGroup: ""
#roleRef:
#  kind: Role
#  name: namespace-reader
#  apiGroup: ""
#  
#---

  
  