####################
### local 
####################

server:
  port: 8080
  forword-headers-strategy: framework
  
  
  
##################################################################################################################################################################################
##  Swagger Target Service Names and Context-paths
##  1. - name : [service name] ==> same as SwaggerUrl group. (see also org.springdoc.core.AbstractSwaggerUiConfigProperties.SwaggerUrl.SwaggerUrl(String group, String url))
##       contextPath : Service's context path
##
##  < Notice >
##  2. Write the [service name] when service do not have context-path(/) like 'icis-cmmn-bmon' or 'icis-cmmn-gwadm'
##    - ex-2: swagger url --> http://icis-cmmn-bmon.sa-app.svc/swagger-ui/index.html
##
##  3. 'icis-samp-ppon' service have context-path 'ppon' then see - name: icis-samp-ppon / contextPath: ppon
##    - ex-3: swagger url --> http://icis-samp-ppon.sa-app.svc/ppon/swagger-ui/index.html
##################################################################################################################################################################################
services:
  target:
  - name: icis-cmmn-bmon
    contextPath: icis-cmmn-bmon
  - name: icis-cmmn-gwadm
    contextPath: icis-cmmn-gwadm
  - name: icis-kos-gw
    contextPath: kos-gw
  - name: icis-samp-inetaplca
    contextPath: inetaplca
  - name: icis-samp-intelnet
    contextPath: intelnet
  - name: icis-samp-ppon
    contextPath: ppon
    
##################################################################################################################################################################################
## spring cloud gateway routes
##  - Add route info of Service when you add service.target
##
## 1. id : Write same name of services.target.name
## 2. uri: Write Kubernetes internal access url and port like 'icis-cmmn-bmon' uri
## 3. predicates: - Path : 
##                          - Add [service name] when service do not have context-path like 'icis-cmmn-bmon'
##                          - Add [context-path] when service have context-path like 'icis-samp-ppon'
## 4. filters: - RewritePath:
##                          - Add [service name] when serivce do not have context-path like 'icis-cmmn-bmon'
##                          - Add [context-path] when service have context-path like 'icis-samp-ppon'
##################################################################################################################################################################################
spring:
  application:
    name: icis-apidoc
  cloud:
    consul:
      enabled: false
    gateway:
      routes:
      - id: icis-cmmn-bmon
        uri: http://icis-cmmn-bmon.sa-app.svc
        predicates:
          - Path=/icis-cmmn-bmon/**
        filters:
          - RewritePath=/icis-cmmn-bmon(?<segment>/?.*), /$\{segment}
      - id: icis-cmmn-gwadm
        uri: http://icis-cmmn-gwadm.sa-app.svc
        predicates:
          - Path=/icis-cmmn-gwadm/**
        filters:
          - RewritePath=/icis-cmmn-gwadm(?<segment>/?.*), /$\{segment}
      - id: icis-kos-gw
        uri: http://icis-kos-gw.sa-app.svc
        predicates:
          - Path=/kos-gw/**
        filters:
          - RewritePath=/kos-gw/(?<segment>/?.*), /kos-gw/$\{segment}
      - id: icis-samp-ppon
        uri: http://icis-samp-ppon.sa-app.svc
        predicates:
          - Path=/ppon/**
        filters:
          - RewritePath=/ppon/(?<segment>/?.*), /ppon/$\{segment}
      - id: icis-samp-inetaplca
        uri: http://icis-samp-inetaplca.sa-app.svc
        predicates:
          - Path=/inetaplca/**
        filters:
          - RewritePath=/inetaplca/(?<segment>/?.*), /inetaplca/$\{segment}
      - id: icis-samp-intelnet
        uri: http://icis-samp-intelnet.sa-app.svc
        predicates:
          - Path=/intelnet/**
        filters:
          - RewritePath=/intelnet/(?<segment>/?.*), /intelnet/$\{segment}


springdoc:  
  swagger-ui:
      operations-sorter: alpha
      tags-sorter: alpha
      disable-swagger-default-url: true
      doc-expansion: none

logging:
  level:
    org.springframework.cloud.gateway: info
    com.kt.icis: debug
    root: INFO
